platform :ios, '9.0'

target 'ios-objc-LUKeychainAccess-demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ios-objc-LUKeychainAccess-demo
  pod 'LUKeychainAccess'

  target 'ios-objc-LUKeychainAccess-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-objc-LUKeychainAccess-demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
